package com.newhope.nlbp.core.job.support;

import java.util.UUID;

import org.quartz.Job;
import org.quartz.JobDataMap;
import org.springframework.util.CollectionUtils;

/**
 * Abstract job class.
 * 
 * @author JackDou
 * @version 2017-4-17
 */
public abstract class AbstractJob implements Job {

	public static final String JOB_NAME_PREFIX = "newhope_job_name_";

	public static final String JOB_GROUP_NAME = "newhope_job_group_name_";

	private JobDataMap attributeMap;

	/**
	 * Constructor
	 */
	public AbstractJob() {
	}

	public abstract String getName();

	public abstract String getGroupName();

	public abstract String getCronExpression();

	protected String genDefaultName() {
		return JOB_NAME_PREFIX + getUUID();
	}

	protected String getGroupDefaultName() {
		return JOB_NAME_PREFIX;
	}

	public void addAttribute(String name, String value) {
		if (CollectionUtils.isEmpty(attributeMap)) {
			attributeMap = new JobDataMap();
		}
		attributeMap.put(name, value);
	}

	public Object getAttribute(String name) {
		if (CollectionUtils.isEmpty(attributeMap) || !attributeMap.containsKey(name)) {
			return null;
		}
		return attributeMap.get(name);
	}

	/**
	 * @return the attributeMap
	 */
	public JobDataMap getAttributeMap() {
		if (CollectionUtils.isEmpty(attributeMap)) {
			return new JobDataMap();
		}
		return attributeMap;
	}

	/**
	 * @param attributeMap
	 *            the attributeMap to set
	 */
	public void setAttributeMap(JobDataMap attributeMap) {
		this.attributeMap = attributeMap;
	}

	/**
	 * 
	 * @return A unique key generated by UUID
	 */
	private static final synchronized String getUUID() {
		return UUID.randomUUID().toString().replace("-", "");
	}
}
